### ISSUE TITLE
Parks endpoint is not longer a table

### ISSUE THREAD

**Issue by mattppal** [tonymet/nps-public-data#1]
Big fan of this project! I just noticed the "parks" endpoint is no longer displayed as a table. It looks like something went wrong on April 24th.

![CleanShot 2024-05-28 at 07 12 21](https://github.com/tonymet/nps-public-data/assets/59450879/4e773093-d697-428c-8012-968a3cd82858)

**Comment by tonymet** [comment]
thanks for catching that I'll look into it.  thanks for your feedback.  can you share how you've been using the dataset?

**Comment by tonymet** [comment]
thanks for your help I was able to catch the config issue.  You also helped me clean up the docker build and workflow to speed things up a lot.  I migrated to https://github.com/tonymet/gcloud-lite which now deploys about 75% faster

```
select count(*) from `nps-public-data.nps_public_data.parks`
471

```

```

SELECT name FROM `nps-public-data.nps_public_data.parks` LIMIT 1000
Federal Hall |  
-- | --
2 | Frederick Law Olmsted |  
3 | National Capital Parks-East |  
4 | Freedom Riders |  
5 | George Washington |  
6 | Cedar Breaks |  
7 | Devils Postpile |  
8 | Isle Royale |  
9 | Jean Lafitte |  
10 | Ice Age |  
11 | Lake Meredith |  
12 | Voyageurs |  
13 | Craters Of The Moon |  
14 | Black Canyon Of The Gunnison |  
15 | Grand Canyon |  
16 | Crater Lake |  
17 | Katahdin Woods and Waters |  
18 | Yellowstone |  
19 | Mount Rainier
```
